# Generated by Django 5.0.6 on 2024-06-09 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKS', '0003_pastmodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastmodification',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BOOKS.book'),
        ),
    ]
